{% set name = "icepap" %}
{% set version = "3.12.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/icepap-{{ version }}.tar.gz
  sha256: 552e11ee9433a28ad114b6d6e23c75a635eb2f0d36ba40ca0f394c78aaeac024

build:
  number: 0
  noarch: python
  entry_points:
    - icepapctl = icepap.cli.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - beautifultable >=1
    - click >=7
    - numpy
    - prompt_toolkit >=3
    - python >={{ python_min }}

test:
  requires:
    - pip
    - python {{ python_min }}
  imports:
    - icepap
  commands:
    - pip check
    - icepapctl --help

about:
  home: https://github.com/ALBA-Synchrotron/pyIcePAP
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Python IcePAP Extension
  description: |
    Python module to configure, control and monitor IcePAP based systems.
    IcePAP is a motor control system developed at the ESRF and optimised
    for high resolution position applications.
  doc_url: https://alba-synchrotron.github.io/pyIcePAP-doc/
  dev_url: https://github.com/ALBA-Synchrotron/pyIcePAP

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
