schema_version: 1

context:
  name: icepap
  version: "3.14.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/icepap-${{ version }}.tar.gz
  sha256: 014ba5392f44b7ac1e097eb6537d4444843a95ac15d284ebd79042f2c9a5e9ce

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - icepapctl = icepap.cli.cli:cli

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
  run:
    - beautifultable >=1
    - click >=7
    - numpy
    - prompt_toolkit >=3
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - icepap
      python_version:
        - ${{ python_min }}.*
        - 3.*
      pip_check: true
  - script:
      - icepapctl --help
    requirements:
      run:
        - python ${{ python_min }}.*

about:
  license: GPL-3.0-or-later
  license_file: LICENSE.txt
  summary: Python IcePAP Extension
  description: |
    Python module to configure, control and monitor IcePAP based systems.
    IcePAP is a motor control system developed at the ESRF and optimised
    for high resolution position applications.
  homepage: https://gitlab.com/icepap-organization/IcePAP
  repository: https://gitlab.com/icepap-organization/IcePAP
  documentation: https://alba-synchrotron.github.io/pyIcePAP-doc/

extra:
  recipe-maintainers:
    - rhomspuron
    - beenje
